# prebuild vignettes for the .zip binary package version
library(devtools)
build_vignettes()
if (!dir.exists("inst/doc")) dir.create("inst/doc")
file.copy(from=paste("doc", list.files("doc"), sep="/"), to="inst/doc", overwrite=TRUE)
if (!dir.exists("inst/Meta")) dir.create("inst/Meta")
file.copy(from=paste("Meta", list.files("Meta"), sep="/"), to="inst/Meta", overwrite=TRUE)
clean_vignettes()
unlink("doc", recursive=TRUE)
unlink("Meta", recursive=TRUE)
